export const ROLES = {
  STUDENT: 'STUDENT',
  INSTRUCTOR: 'INSTRUCTOR',
  PARENT: 'PARENT',
  ADMINISTRATOR: 'ADMINISTRATOR',
  STUDENT_SERVICES: 'STUDENT_SERVICES',
  COMMUNITY_SERVICES: 'COMMUNITY_SERVICES',
  PUBLIC: 'PUBLIC',
} as const;

export type RoleKey = keyof typeof ROLES;

export const ROLE_THEMES = {
  STUDENT: {
    name: 'Student',
    primary: '#7C3AED',
    gradient: 'from-purple-600 to-violet-600',
    bgGradient: 'from-purple-50 to-violet-50',
    darkBgGradient: 'from-purple-950 to-violet-950',
    accent: 'purple',
    icon: '📚',
  },
  INSTRUCTOR: {
    name: 'Instructor',
    primary: '#F59E0B',
    gradient: 'from-amber-500 to-orange-500',
    bgGradient: 'from-amber-50 to-orange-50',
    darkBgGradient: 'from-amber-950 to-orange-950',
    accent: 'amber',
    icon: '🎓',
  },
  PARENT: {
    name: 'Parent',
    primary: '#10B981',
    gradient: 'from-emerald-500 to-green-500',
    bgGradient: 'from-emerald-50 to-green-50',
    darkBgGradient: 'from-emerald-950 to-green-950',
    accent: 'emerald',
    icon: '👨‍👩‍👧‍👦',
  },
  ADMINISTRATOR: {
    name: 'Administrator',
    primary: '#D97706',
    gradient: 'from-orange-500 to-amber-600',
    bgGradient: 'from-orange-50 to-amber-50',
    darkBgGradient: 'from-orange-950 to-amber-950',
    accent: 'orange',
    icon: '⚙️',
  },
  STUDENT_SERVICES: {
    name: 'Student Services',
    primary: '#3B82F6',
    gradient: 'from-blue-500 to-indigo-500',
    bgGradient: 'from-blue-50 to-indigo-50',
    darkBgGradient: 'from-blue-950 to-indigo-950',
    accent: 'blue',
    icon: '💙',
  },
  COMMUNITY_SERVICES: {
    name: 'Community Services',
    primary: '#14B8A6',
    gradient: 'from-teal-500 to-cyan-500',
    bgGradient: 'from-teal-50 to-cyan-50',
    darkBgGradient: 'from-teal-950 to-cyan-950',
    accent: 'teal',
    icon: '🤝',
  },
  PUBLIC: {
    name: 'Public',
    primary: '#64748B',
    gradient: 'from-slate-500 to-gray-600',
    bgGradient: 'from-slate-50 to-gray-50',
    darkBgGradient: 'from-slate-950 to-gray-950',
    accent: 'slate',
    icon: '🌐',
  },
} as const;

export const NAV_ITEMS = {
  STUDENT: [
    { name: 'Home', href: '/student', icon: 'Home' },
    { name: 'Calendar', href: '/student/calendar', icon: 'Calendar' },
    { name: 'Messages', href: '/student/messages', icon: 'MessageSquare' },
    { name: 'My Office', href: '/student/office', icon: 'Briefcase' },
    { name: 'Learning', href: '/student/learning', icon: 'BookOpen' },
    { name: 'Work', href: '/student/work', icon: 'FileText' },
    { name: 'Future', href: '/student/future', icon: 'Rocket' },
    { name: 'Teams', href: '/student/teams', icon: 'Users' },
    { name: 'AI Assistant', href: '/student/ai', icon: 'Bot' },
    { name: 'Settings', href: '/student/settings', icon: 'Settings' },
  ],
  INSTRUCTOR: [
    { name: 'Home', href: '/instructor', icon: 'Home' },
    { name: 'Calendar', href: '/instructor/calendar', icon: 'Calendar' },
    { name: 'Messages', href: '/instructor/messages', icon: 'MessageSquare' },
    { name: 'Assistant', href: '/instructor/assistant', icon: 'Bot' },
    { name: 'My Office', href: '/instructor/office', icon: 'Briefcase' },
    { name: 'Curriculum', href: '/instructor/curriculum', icon: 'BookOpen' },
    { name: 'Gradebook', href: '/instructor/gradebook', icon: 'ClipboardList' },
    { name: 'Partnerships', href: '/instructor/partnerships', icon: 'Handshake' },
    { name: 'Development', href: '/instructor/development', icon: 'GraduationCap' },
    { name: 'Learning Space', href: '/instructor/space', icon: 'Layout' },
    { name: 'My Brand', href: '/instructor/brand', icon: 'Palette' },
    { name: 'Media', href: '/instructor/media', icon: 'Video' },
    { name: 'Settings', href: '/instructor/settings', icon: 'Settings' },
  ],
  PARENT: [
    { name: 'Home', href: '/parent', icon: 'Home' },
    { name: 'Calendar', href: '/parent/calendar', icon: 'Calendar' },
    { name: 'Messages', href: '/parent/messages', icon: 'MessageSquare' },
    { name: 'Assistant', href: '/parent/assistant', icon: 'Bot' },
    { name: 'My Profile', href: '/parent/profile', icon: 'User' },
    { name: 'Our Info', href: '/parent/info', icon: 'FileText' },
    { name: 'Services', href: '/parent/services', icon: 'Heart' },
    { name: 'Children', href: '/parent/children', icon: 'Users' },
    { name: 'Settings', href: '/parent/settings', icon: 'Settings' },
  ],
  ADMINISTRATOR: [
    { name: 'Home', href: '/admin', icon: 'Home' },
    { name: 'Calendar', href: '/admin/calendar', icon: 'Calendar' },
    { name: 'Messages', href: '/admin/messages', icon: 'MessageSquare' },
    { name: 'Assistant', href: '/admin/assistant', icon: 'Bot' },
    { name: 'Office', href: '/admin/office', icon: 'Building2' },
    { name: 'Budget', href: '/admin/budget', icon: 'DollarSign' },
    { name: 'Reports', href: '/admin/reports', icon: 'BarChart3' },
    { name: 'Data', href: '/admin/data', icon: 'Database' },
    { name: 'Work', href: '/admin/work', icon: 'Briefcase' },
    { name: 'Info', href: '/admin/info', icon: 'FileText' },
    { name: 'Spaces', href: '/admin/spaces', icon: 'Layout' },
    { name: 'Management', href: '/admin/management', icon: 'Users' },
    { name: 'Services', href: '/admin/services', icon: 'Heart' },
    { name: 'Settings', href: '/admin/settings', icon: 'Settings' },
  ],
  STUDENT_SERVICES: [
    { name: 'Home', href: '/services', icon: 'Home' },
    { name: 'Calendar', href: '/services/calendar', icon: 'Calendar' },
    { name: 'Messages', href: '/services/messages', icon: 'MessageSquare' },
    { name: 'Assistant', href: '/services/assistant', icon: 'Bot' },
    { name: 'Special Ed', href: '/services/special-ed', icon: 'Heart' },
    { name: 'Physical Therapy', href: '/services/pt', icon: 'Activity' },
    { name: 'Speech', href: '/services/speech', icon: 'Mic' },
    { name: 'Counseling', href: '/services/counseling', icon: 'HeartHandshake' },
    { name: 'Guidance', href: '/services/guidance', icon: 'Compass' },
    { name: 'Settings', href: '/services/settings', icon: 'Settings' },
  ],
  COMMUNITY_SERVICES: [
    { name: 'Home', href: '/community', icon: 'Home' },
    { name: 'Calendar', href: '/community/calendar', icon: 'Calendar' },
    { name: 'Messages', href: '/community/messages', icon: 'MessageSquare' },
    { name: 'Assistant', href: '/community/assistant', icon: 'Bot' },
    { name: 'Careers', href: '/community/careers', icon: 'Briefcase' },
    { name: 'College', href: '/community/college', icon: 'GraduationCap' },
    { name: 'Safety', href: '/community/safety', icon: 'Shield' },
    { name: 'Facilities', href: '/community/facilities', icon: 'Building' },
    { name: 'Library', href: '/community/library', icon: 'Library' },
    { name: 'Partners', href: '/community/partners', icon: 'Handshake' },
    { name: 'Settings', href: '/community/settings', icon: 'Settings' },
  ],
  PUBLIC: [
    { name: 'Home', href: '/public', icon: 'Home' },
    { name: 'Calendar', href: '/public/calendar', icon: 'Calendar' },
    { name: 'Contact', href: '/public/contact', icon: 'Mail' },
    { name: 'Events', href: '/public/events', icon: 'PartyPopper' },
    { name: 'Postings', href: '/public/postings', icon: 'Newspaper' },
    { name: 'Galleries', href: '/public/galleries', icon: 'Image' },
    { name: 'Volunteer', href: '/public/volunteer', icon: 'Heart' },
    { name: 'Jobs', href: '/public/jobs', icon: 'Briefcase' },
    { name: 'Classes', href: '/public/classes', icon: 'BookOpen' },
  ],
} as const;

export const GRADE_SCALES = {
  STANDARD: [
    { letter: 'A+', min: 97, max: 100 },
    { letter: 'A', min: 93, max: 96 },
    { letter: 'A-', min: 90, max: 92 },
    { letter: 'B+', min: 87, max: 89 },
    { letter: 'B', min: 83, max: 86 },
    { letter: 'B-', min: 80, max: 82 },
    { letter: 'C+', min: 77, max: 79 },
    { letter: 'C', min: 73, max: 76 },
    { letter: 'C-', min: 70, max: 72 },
    { letter: 'D+', min: 67, max: 69 },
    { letter: 'D', min: 63, max: 66 },
    { letter: 'D-', min: 60, max: 62 },
    { letter: 'F', min: 0, max: 59 },
  ],
  PASS_FAIL: [
    { letter: 'P', min: 60, max: 100 },
    { letter: 'F', min: 0, max: 59 },
  ],
} as const;

export const FILE_UPLOAD_LIMITS = {
  MAX_FILE_SIZE: 50 * 1024 * 1024, // 50MB
  MAX_TOTAL_SIZE: 200 * 1024 * 1024, // 200MB
  ALLOWED_TYPES: [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain',
    'text/csv',
    'video/mp4',
    'video/webm',
    'audio/mpeg',
    'audio/wav',
  ],
} as const;

export const NOTIFICATION_TYPES = {
  MESSAGE: { icon: 'MessageSquare', color: 'blue' },
  ASSIGNMENT: { icon: 'FileText', color: 'purple' },
  GRADE: { icon: 'Award', color: 'green' },
  ANNOUNCEMENT: { icon: 'Megaphone', color: 'orange' },
  CALENDAR: { icon: 'Calendar', color: 'indigo' },
  TASK: { icon: 'CheckSquare', color: 'teal' },
  SYSTEM: { icon: 'Bell', color: 'gray' },
  ALERT: { icon: 'AlertTriangle', color: 'red' },
} as const;
